name: Manual Run

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Select which tests to run (all, specs, api)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - specs
          - api
      browser:
        description: 'Browser project (chrome, msedge)'
        required: false
        default: 'chrome'
      tag:
        description: 'Run only tests with given @tag (leave empty for all tests)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    env:
      OPENLIB_EMAIL: ${{ secrets.OPENLIB_EMAIL }}
      OPENLIB_PASSWORD: ${{ secrets.OPENLIB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --registry=https://registry.npmjs.org/

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          mkdir -p test-results
          FOLDER="${{ github.event.inputs.folder }}"
          BROWSER="${{ github.event.inputs.browser }}"
          TAG="${{ github.event.inputs.tag }}"

          if [ "$FOLDER" = "all" ]; then
            TARGET="tests"
          else
            TARGET="tests/$FOLDER"
          fi
          
          if [ -z "$TAG" ]; then
            echo "Running all tests in $TARGET with $BROWSER"
            npx playwright test "$TARGET" --project="$BROWSER"
          else
            echo "Running tests in $TARGET with $BROWSER and tag $TAG"
            npx playwright test "$TARGET" --project="$BROWSER" --grep "$TAG"
          fi

      - name: Add results to GitHub Summary
        if: always()
        run: |
          echo "## Playwright Test Results" >> $GITHUB_STEP_SUMMARY
          if [ -f test-results/results.xml ]; then
            npx junit-viewer --results=test-results/results.xml --summary >> $GITHUB_STEP_SUMMARY
          else
            echo "No JUnit results found." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload traces and videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: test-results
